version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "cognito-lambda"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-sfx4yt2qyeb9"
s3_prefix = "cognito-lambda"
region = "eu-central-1"
profile = "gokhan"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
