AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  cognito-lambda

Globals:
  Function:
    Timeout: 3

Resources:
  FlaskAPIFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: app/
      Handler: main.lambda_handler
      Runtime: python3.8
      Environment:
        Variables: 
          COGNITO_USER_POOL_ID: eu-central-1_V0TkvDe3v
          COGNITO_APP_CLIENT_ID: 75nouu1kqjhvqlbiiasd6dgpld
      Events:
        HelloWorld:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: any
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref AccountTable
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - cognito-idp:*
              Resource: '*'

  AccountTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      PrimaryKey: 
        Name: username
        Type: String
      TableName: account
